name: CI Runner
permissions:
  checks: write
  actions: read
  contents: read
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 8 11 9 *' # 8AM 9/11 UTC, 1AM 9/11 PT
jobs:
  run-autograding-tests:
    runs-on: self-hosted
    container: ghcr.io/sfu-cmpt-201/base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grader
        uses: SFU-CMPT-201/graders/.github/actions/a0@main
      - name: Autograding Reporter
        uses: SFU-CMPT-201/autograding-grading-reporter@v1
      - name: Clean up
        run: |
          rm -rf ./* ./.* > /dev/null 2>&1 || true
        if: ${{ always() }}
